---
- hosts: localhost
  name: Install Sublime Text 3
  become: yes
  tasks:
    - name: Install Sublime Text repo key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
      tags:
        - sublime-text

    - name: Ensure APT works with HTTPS sources
      apt:
        name: apt-transport-https
      tags:
        - sublime-text

    - name: Sublime Text 3 PPA (webupd8team)
      apt_repository:
        repo: "deb https://download.sublimetext.com/ apt/stable/"
        update_cache: yes
      tags:
        - sublime-text

    - name: Sublime Text 3
      apt:
        name: sublime-text
      tags:
        - sublime-text
